// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfgoma021-nisZq7jBwZWJcvc1P-kz1Pg',
    appId: '1:652953214982:web:144d9ea252dbd7b1a26387',
    messagingSenderId: '652953214982',
    projectId: 'inventario-app-2026',
    authDomain: 'inventario-app-2026.firebaseapp.com',
    storageBucket: 'inventario-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3RKQjuP3EkwCQONI2fLXiyC7G-rdwynk',
    appId: '1:652953214982:android:ec736fd5086ffa2da26387',
    messagingSenderId: '652953214982',
    projectId: 'inventario-app-2026',
    storageBucket: 'inventario-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB1u3w5ibwvkoh0PCsndiPiFLUm5CnQGo',
    appId: '1:652953214982:ios:750da3528db32ad2a26387',
    messagingSenderId: '652953214982',
    projectId: 'inventario-app-2026',
    storageBucket: 'inventario-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.inventarioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB1u3w5ibwvkoh0PCsndiPiFLUm5CnQGo',
    appId: '1:652953214982:ios:750da3528db32ad2a26387',
    messagingSenderId: '652953214982',
    projectId: 'inventario-app-2026',
    storageBucket: 'inventario-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.inventarioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfgoma021-nisZq7jBwZWJcvc1P-kz1Pg',
    appId: '1:652953214982:web:6ba97bf811f8287fa26387',
    messagingSenderId: '652953214982',
    projectId: 'inventario-app-2026',
    authDomain: 'inventario-app-2026.firebaseapp.com',
    storageBucket: 'inventario-app-2026.firebasestorage.app',
  );
}
